### PR TITLE
merge remote branch strasdat/master

### PR DESCRIPTION
**Pull request by qh-huang**
Lots of issues have already been solved in Sophus. Merge all those commits for ROS-packages which rely on sophus.

### CODE REVIEW

**Comment by stonier** [comment]
While I'm excited about the work finally going back into sophus upstream, I have to also consider API changes within a ROS distro. There's likely to be more than a few users relying on this API staying stable for the duration of the distro.

What ros distro are you using?

**Comment by stonier** [comment]
I could get this into a development branch that you can use and be ready to release it with the next rosdistro.

**Comment by qh-huang** [comment]
I currently use indigo, is it possible to update indigo as well?
I made this change because my library relies on Sophus upstream but there's a sub-project using that library and ROS, and there's compatible issue occured.

**Comment by stonier** [comment]
I should not update indigo for the same reason - it would cause API changes for people who already have code that relies on it.

Can you compile your library and the sub-project in the same catkin workspace? Are you able to update the sub-project for sophus api changes? If you can do that, I can put these changes into a 'devel' branch and you can put this branch in your workspace. This source workspace version of sophus will override the binary version in `/opt/ros/indigo`.

The number of other packages in the catkin-verse depending on sophus are pretty finite so I expect you should be able to handle an upstream sophus in your source workspace like this.

**Comment by qh-huang** [comment]
OK. Please put the change in devel branch. Thank you!

**Comment by stonier** [comment]
Just a heads up, the `devel` branch is now ament compatible. I've left a branch around called `catkin-devel` with the contents above.

**Comment by qh-huang** [comment]
OK. Thanks!

**Pull request merged**
